import { getFeature, type BaselineLevel } from './baseline.ts';

/**
 * The condition under which an authored gotcha stops being true.
 *
 * Prose about a browser quirk can't be regenerated by a machine, but it can
 * declare *why* it is currently true. When that premise expires the block stops
 * rendering, so the site loses a caveat rather than publishing a falsehood.
 */
export type StaleWhen =
  | { feature: string; browser: string; supported: true }
  | { feature: string; baseline: 'low' | 'high' };

export interface StaleResult {
  stale: boolean;
  /** Human-readable explanation, used in the PR body and build report. */
  reason: string;
}

const LEVEL_RANK: Record<BaselineLevel, number> = {
  limited: 0,
  newly: 1,
  widely: 2,
};

export function evaluateStaleWhen(when: StaleWhen): StaleResult {
  const info = getFeature(when.feature);

  if ('browser' in when) {
    const entry = [...info.desktop, ...info.mobile].find((b) => b.id === when.browser);
    if (!entry) {
      throw new Error(
        `[gotchas] staleWhen references unknown browser "${when.browser}" ` +
          `for feature "${when.feature}".`,
      );
    }
    const nowSupported = entry.state !== 'none';
    return {
      stale: nowSupported,
      reason: nowSupported
        ? `${entry.name} now supports ${when.feature} (since ${entry.version})`
        : `${entry.name} still does not support ${when.feature}`,
    };
  }

  const target = when.baseline === 'high' ? 'widely' : 'newly';
  const reached = LEVEL_RANK[info.level] >= LEVEL_RANK[target as BaselineLevel];
  return {
    stale: reached,
    reason: reached
      ? `${when.feature} has reached Baseline ${when.baseline} (${info.level})`
      : `${when.feature} has not reached Baseline ${when.baseline} (currently ${info.level})`,
  };
}
